#!/bin/bash
clear
echo "================================================================="
echo ""
echo "  ██████╗ ███████╗ ██████╗  ██████╗ ██╗   ██╗███████╗██████╗ ██████╗ "
echo "  ██╔══██╗██╔════╝██╔════╝ ██╔═══██╗██║   ██║██╔════╝██╔══██╗██╔══██╗"
echo "  ██████╔╝█████╗  ██║      ██║   ██║██║   ██║█████╗  ██████╔╝██████╔╝"
echo "  ██╔══██╗██╔══╝  ██║      ██║   ██║╚██╗ ██╔╝██╔══╝  ██╔══██╗██╔══██╗"
echo "  ██║  ██║███████╗╚██████╗ ╚██████╔╝ ╚████╔╝ ███████╗██║  ██║██║  ██║"
echo "  ╚═╝  ╚═╝╚══════╝ ╚═════╝  ╚═════╝   ╚═══╝  ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝"
echo ""
echo "  Recover Droid - Professional Data Recovery & Forensics Tool"
echo "================================================================="
echo ""
echo "  Welcome! You can now run the recovery commands below."
echo ""
echo "  Available Commands:"
echo "    1. List all connected drives:"
echo "       sudo ./recover-droid list"
echo ""
echo "    2. Scan a drive (e.g. drive /dev/sda1) for deleted files:"
echo "       sudo ./recover-droid scan /dev/sda1"
echo ""
echo "    3. Recover file ID 1 to ./Recovered:"
echo "       sudo ./recover-droid recover /dev/sda1 1 ./Recovered"
echo ""
echo "    4. Perform signature-based carving (e.g. drive /dev/sda) to ./Recovered:"
echo "       sudo ./recover-droid carve /dev/sda ./Recovered"
echo ""
echo "================================================================="
echo " IMPORTANT: Please run ./recover-droid with sudo to access raw USBs!"
echo "================================================================="
echo ""
bash
